/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.AdminRole;

import Business.DB4OUtil.DB4OUtil;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Varada
 */
public class AdminWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form AdminWorkAreaJPanel
     */
    private DB4OUtil dB4OUtil = DB4OUtil.getInstance();
    JPanel userProcessContainer;
    EcoSystem ecosystem;
    Enterprise enterprise;
    public AdminWorkAreaJPanel(JPanel userProcessContainer, Enterprise enterprise, EcoSystem ecosystem) {
        initComponents();
        this.enterprise = enterprise;
        this.userProcessContainer = userProcessContainer;
        this.ecosystem = ecosystem;
        AdminHomeJPanel adminHomePanel = new AdminHomeJPanel(jPanel2, enterprise);
        jPanel2.add("adminHomeJPanel", adminHomePanel);
        CardLayout layout = (CardLayout) jPanel2.getLayout();
        layout.next(jPanel2);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        manageOrganizationLbl = new javax.swing.JLabel();
        addEmployeeLbl = new javax.swing.JLabel();
        registerEmployeeLbl = new javax.swing.JLabel();
        logoutLbl = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();

        jPanel1.setBackground(new java.awt.Color(71, 120, 197));

        manageOrganizationLbl.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        manageOrganizationLbl.setForeground(new java.awt.Color(255, 255, 255));
        manageOrganizationLbl.setText("Manage Organization");
        manageOrganizationLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                manageOrganizationLblMouseClicked(evt);
            }
        });

        addEmployeeLbl.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        addEmployeeLbl.setForeground(new java.awt.Color(255, 255, 255));
        addEmployeeLbl.setText("Add Employee");
        addEmployeeLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addEmployeeLblMouseClicked(evt);
            }
        });

        registerEmployeeLbl.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        registerEmployeeLbl.setForeground(new java.awt.Color(255, 255, 255));
        registerEmployeeLbl.setText("Create User Account");
        registerEmployeeLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                registerEmployeeLblMouseClicked(evt);
            }
        });

        logoutLbl.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        logoutLbl.setText("Logout");
        logoutLbl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutLblActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(manageOrganizationLbl)
                    .addComponent(addEmployeeLbl)
                    .addComponent(registerEmployeeLbl)
                    .addComponent(logoutLbl))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(manageOrganizationLbl)
                .addGap(43, 43, 43)
                .addComponent(addEmployeeLbl)
                .addGap(45, 45, 45)
                .addComponent(registerEmployeeLbl)
                .addGap(43, 43, 43)
                .addComponent(logoutLbl)
                .addContainerGap(128, Short.MAX_VALUE))
        );

        jSplitPane1.setLeftComponent(jPanel1);

        jPanel2.setBackground(new java.awt.Color(120, 168, 252));
        jPanel2.setLayout(new java.awt.CardLayout());
        jSplitPane1.setRightComponent(jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 644, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void manageOrganizationLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manageOrganizationLblMouseClicked
        // TODO add your handling code here:
        ManageOrganizationJPanel manageOrganizationJPanel = new ManageOrganizationJPanel(jPanel2, enterprise);
        jPanel2.add("manageOrganizationJPanel", manageOrganizationJPanel);
        CardLayout layout = (CardLayout) jPanel2.getLayout();
        layout.next(jPanel2);
    }//GEN-LAST:event_manageOrganizationLblMouseClicked

    private void addEmployeeLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addEmployeeLblMouseClicked
        // TODO add your handling code here:
        ManageEmployeeJPanel manageEmployeeJPanel = new ManageEmployeeJPanel(jPanel2, enterprise.getOrganizationDirectory());
        jPanel2.add("manageEmployeeJPanel", manageEmployeeJPanel);
        CardLayout layout = (CardLayout) jPanel2.getLayout();
        layout.next(jPanel2);
        
    }//GEN-LAST:event_addEmployeeLblMouseClicked

    private void logoutLblActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutLblActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
        dB4OUtil.storeSystem(ecosystem);
    }//GEN-LAST:event_logoutLblActionPerformed

    private void registerEmployeeLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registerEmployeeLblMouseClicked
        // TODO add your handling code here:
        ManageUserAccountJPanel muajp = new ManageUserAccountJPanel(jPanel2, enterprise);
        jPanel2.add("ManageUserAccountJPanel", muajp);
        CardLayout layout = (CardLayout) jPanel2.getLayout();
        layout.next(jPanel2);
    }//GEN-LAST:event_registerEmployeeLblMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addEmployeeLbl;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JButton logoutLbl;
    private javax.swing.JLabel manageOrganizationLbl;
    private javax.swing.JLabel registerEmployeeLbl;
    // End of variables declaration//GEN-END:variables
}
