/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.NurseRole;

import Business.Drug.Drug;
import Business.Enterprise.HelpCenterEnterprise;
import Business.Organization.Organization;
import Business.Organization.RelationManagerOrganization;
import Business.UserAccount.UserAccount;
import Business.WorkRequest.SupplyDrugsWorkRequest;
import Business.WorkRequest.WorkRequest;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author amans
 */
public class ManageInventoryJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageInventoryJPanel
     */
    JPanel jpanel;
    HelpCenterEnterprise enterprise;
    UserAccount account;
    DateFormat df = new SimpleDateFormat("MM/dd/yyyy");
    public ManageInventoryJPanel(JPanel jpanel, HelpCenterEnterprise enterprise, UserAccount account){
        initComponents();
        this.jpanel = jpanel;
        this.enterprise = enterprise;
        this.account = account;
        populateInventoryTable();
        populateRequestsTable();
    }

    private void populateInventoryTable(){
        DefaultTableModel model = (DefaultTableModel)inventoryTbl.getModel();
        DateFormat df = new SimpleDateFormat("MM/dd/yyyy");
        Date todayDate = new Date();
        try{
            todayDate = df.parse(df.format(todayDate));
        }catch(Exception e){
            System.out.println(e);
        }
//        
        model.setRowCount(0);
        Object []row = new Object[4];
        for(Drug drug: enterprise.getDrugList().values()){
                Date drugDate = new Date();
                try{
                    drugDate = df.parse(df.format(drug.getDate()));
                }catch(Exception e){
                    System.out.println(e);
                }
                if(filterComboBox.getSelectedItem().toString().equals("Low on Stock")&&drug.getQuantity()<=5){
                    row[0] = drug;
                    row[1] = drug.getName();
                    row[2] = drug.getQuantity();
                    row[3] = drug.getDate();
                    model.addRow(row);
                }else if(filterComboBox.getSelectedItem().equals("Expired Drugs")&& todayDate.after(drugDate)){
                    row[0] = drug;
                    row[1] = drug.getName();
                    row[2] = drug.getQuantity();
                    row[3] = drug.getDate();
                    model.addRow(row);
                }else if(filterComboBox.getSelectedItem().equals("All drugs")){
                    row[0] = drug;
                    row[1] = drug.getName();
                    row[2] = drug.getQuantity();
                    row[3] = drug.getDate();
                    model.addRow(row);
                }
        }
    }
    
    private void populateRequestsTable(){
        DefaultTableModel model = (DefaultTableModel)requestTbl.getModel();
        model.setRowCount(0);
        Object []row = new Object[4];
        
        for(WorkRequest request: account.getWorkQueue().getWorkRequestList()){
            if(request instanceof SupplyDrugsWorkRequest){
               SupplyDrugsWorkRequest supply = (SupplyDrugsWorkRequest)request;
               Drug drug = supply.getDrug();
               row[0] = drug;
               row[1] = drug.getName();
               row[2] = supply.getQuantity();
               row[3] = supply.getTestStatus();
               model.addRow(row);   
            }
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        filterComboBox = new javax.swing.JComboBox<String>();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        inventoryTbl = new javax.swing.JTable();
        raiseRequestBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        quantityTxtField = new javax.swing.JTextField();
        discardBtn = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        requestTbl = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        setBackground(new java.awt.Color(120, 168, 252));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        filterComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Low on Stock", "Expired Drugs", "All drugs" }));
        filterComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                filterComboBoxItemStateChanged(evt);
            }
        });
        add(filterComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(245, 78, 147, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Filter By:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(152, 77, -1, -1));

        inventoryTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Drug Id", "Drug Name", "Quantity", "Date of Expiry"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(inventoryTbl);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(111, 120, 514, 219));

        raiseRequestBtn.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        raiseRequestBtn.setText("Raise Request");
        raiseRequestBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                raiseRequestBtnActionPerformed(evt);
            }
        });
        add(raiseRequestBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(364, 434, 145, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Quantity to Request: ");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(164, 369, -1, -1));
        add(quantityTxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(361, 370, 145, -1));

        discardBtn.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        discardBtn.setText("Discard");
        discardBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                discardBtnActionPerformed(evt);
            }
        });
        add(discardBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 434, -1, -1));

        requestTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Drug Id", "Drug Name", "Quantity Requested", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(requestTbl);

        add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(109, 504, 520, 121));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Manage Inventory");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(266, 16, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void raiseRequestBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_raiseRequestBtnActionPerformed
        // TODO add your handling code here:
        Drug drug = (Drug)inventoryTbl.getValueAt(inventoryTbl.getSelectedRow(), 0);
        SupplyDrugsWorkRequest drugRequest = new SupplyDrugsWorkRequest();
        int quantity = Integer.parseInt(quantityTxtField.getText());
        WorkRequest.WorkStatusType type = WorkRequest.WorkStatusType.Pending;
        drugRequest.setTestStatus(type.getValue());
        drugRequest.setDrug(drug);
        drugRequest.setQuantity(quantity);
        drugRequest.setSender(account);
        drugRequest.setEnterprise(enterprise);
        try{drugRequest.setRequestDate(df.parse(String.valueOf(new Date())));}
        catch(Exception e){
            System.out.println(e);
        }
        account.getWorkQueue().getWorkRequestList().add(drugRequest);
        for( Organization org: enterprise.getOrganizationDirectory().getOrganizationList()){
            if(org instanceof RelationManagerOrganization){
                org.getWorkQueue().getWorkRequestList().add(drugRequest);
                break;
            }
        }
        populateRequestsTable();
    }//GEN-LAST:event_raiseRequestBtnActionPerformed

    private void discardBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_discardBtnActionPerformed
        // TODO add your handling code here:
        Date todayDate = new Date();
        try{
            todayDate = this.df.parse(df.format(todayDate));
        }catch(ParseException e){
                System.out.println(e);
            }
        Drug drug = (Drug)inventoryTbl.getValueAt(inventoryTbl.getSelectedRow(), 0);
        drug.setQuantity(0);
        drug.setDate(todayDate);
        enterprise.getDrugList().put(drug.getId(), drug);
        populateInventoryTable();
    }//GEN-LAST:event_discardBtnActionPerformed

    private void filterComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_filterComboBoxItemStateChanged
        // TODO add your handling code here:
        populateInventoryTable();
    }//GEN-LAST:event_filterComboBoxItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton discardBtn;
    private javax.swing.JComboBox<String> filterComboBox;
    private javax.swing.JTable inventoryTbl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField quantityTxtField;
    private javax.swing.JButton raiseRequestBtn;
    private javax.swing.JTable requestTbl;
    // End of variables declaration//GEN-END:variables
}
