/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.NurseRole;

import Business.DB4OUtil.DB4OUtil;
import Business.EcoSystem;
import java.awt.CardLayout;

import Business.Enterprise.HelpCenterEnterprise;
import Business.Organization.NurseOrganization;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Yash Lekhwani
 */
public class NurseWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form NurseWorkAreaJPanel
     */

    JPanel jpanel;
    HelpCenterEnterprise enterprise;
    EcoSystem ecosystem;
    Organization org;
    UserAccount account;
    private DB4OUtil dB4OUtil = DB4OUtil.getInstance();
    NurseWorkAreaHomeJPanel nh;
    public NurseWorkAreaJPanel(JPanel jpanel, EcoSystem ecosystem, HelpCenterEnterprise enterprise, UserAccount account) {
        initComponents();
        this.jpanel = jpanel;
        this.enterprise = enterprise;
        this.ecosystem=ecosystem;
        this.account = account;
         for(Organization org : enterprise.getOrganizationDirectory().getOrganizationList()){
            if(org instanceof NurseOrganization)
                this.org = org;
        }
        this.nh = new NurseWorkAreaHomeJPanel(jPanel2, org, account);
        jPanel2.add("NurseWorkAreaHomeJPanel", nh);
        CardLayout layout = (CardLayout)jPanel2.getLayout();
        layout.next(jPanel2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        collectSamples = new javax.swing.JLabel();
        prescribeMedicines = new javax.swing.JLabel();
        manageEnterpriseAdminLbl = new javax.swing.JLabel();
        logout = new javax.swing.JButton();
        manageInventory = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();

        jMenuItem1.setText("jMenuItem1");

        jPanel1.setBackground(new java.awt.Color(71, 120, 197));

        collectSamples.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        collectSamples.setForeground(new java.awt.Color(255, 255, 255));
        collectSamples.setText("Collect Samples");
        collectSamples.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                collectSamplesMouseClicked(evt);
            }
        });

        prescribeMedicines.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        prescribeMedicines.setForeground(new java.awt.Color(255, 255, 255));
        prescribeMedicines.setText("Prescribe Medicines");
        prescribeMedicines.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                prescribeMedicinesMouseClicked(evt);
            }
        });

        manageEnterpriseAdminLbl.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        manageEnterpriseAdminLbl.setForeground(new java.awt.Color(255, 255, 255));
        manageEnterpriseAdminLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                manageEnterpriseAdminLblMouseClicked(evt);
            }
        });

        logout.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        logout.setText("LOGOUT");
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });

        manageInventory.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        manageInventory.setForeground(new java.awt.Color(255, 255, 255));
        manageInventory.setText("Manage Inventory");
        manageInventory.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                manageInventoryMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(prescribeMedicines)
                    .addComponent(collectSamples)
                    .addComponent(manageEnterpriseAdminLbl)
                    .addComponent(logout)
                    .addComponent(manageInventory))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(collectSamples)
                .addGap(27, 27, 27)
                .addComponent(prescribeMedicines)
                .addGap(27, 27, 27)
                .addComponent(manageInventory)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(manageEnterpriseAdminLbl)
                .addGap(61, 61, 61)
                .addComponent(logout)
                .addContainerGap(102, Short.MAX_VALUE))
        );

        jSplitPane1.setLeftComponent(jPanel1);

        jPanel2.setLayout(new java.awt.CardLayout());
        jSplitPane1.setRightComponent(jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 584, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void collectSamplesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_collectSamplesMouseClicked
        // TODO add your handling code here:
        if(nh.getSelectedRecord() == null){
            JOptionPane.showMessageDialog(null, "Please select a row from patient table");
            return;
        }
        CollectSamples cs = new CollectSamples(jPanel2, enterprise, nh.getSelectedRecord(), account);
        jPanel2.add("CollectSamples", cs);
        CardLayout layout = (CardLayout)jPanel2.getLayout();
        layout.next(jPanel2);

    }//GEN-LAST:event_collectSamplesMouseClicked

    private void prescribeMedicinesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_prescribeMedicinesMouseClicked
        if(nh.getSelectedRecord() == null){
            JOptionPane.showMessageDialog(null, "Please select a row from patient table");
            return;
        }
        PrescribeMedicines pm = new PrescribeMedicines(jPanel2, enterprise, nh.getSelectedRecord());
        jPanel2.add("PrescribeMedicines", pm);
        CardLayout layout = (CardLayout)jPanel2.getLayout();
        layout.next(jPanel2);
    }//GEN-LAST:event_prescribeMedicinesMouseClicked

  
    private void manageEnterpriseAdminLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manageEnterpriseAdminLblMouseClicked
      
    }//GEN-LAST:event_manageEnterpriseAdminLblMouseClicked

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        // TODO add your handling code here:
        jpanel.remove(this);
        CardLayout layout = (CardLayout)jpanel.getLayout();
        layout.previous(jpanel);
        dB4OUtil.storeSystem(ecosystem);
    }//GEN-LAST:event_logoutActionPerformed

    private void manageInventoryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manageInventoryMouseClicked
        // TODO add your handling code here:
        ManageInventoryJPanel mijp = new ManageInventoryJPanel(jPanel2, enterprise, account);
        jPanel2.add("ManageInventory", mijp);
        CardLayout layout = (CardLayout)jPanel2.getLayout();
        layout.next(jPanel2);
    }//GEN-LAST:event_manageInventoryMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel collectSamples;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JButton logout;
    private javax.swing.JLabel manageEnterpriseAdminLbl;
    private javax.swing.JLabel manageInventory;
    private javax.swing.JLabel prescribeMedicines;
    // End of variables declaration//GEN-END:variables
}
