/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.NurseRole;

import Business.Enterprise.Enterprise;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.WorkRequest.LabTestWorkRequest;
import Business.WorkRequest.PrescribeMedsWorkRequest;
import Business.WorkRequest.SupplyDrugsWorkRequest;
import Business.WorkRequest.WorkRequest;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Yash Lekhwani
 */
public class NurseWorkAreaHomeJPanel extends javax.swing.JPanel {
    
    JPanel jPanel;
    Organization organization;
    UserAccount account;
    /**
     * Creates new form NurseWorkAreaHomeJPanel
     */
   

    NurseWorkAreaHomeJPanel(JPanel jPanel2, Organization organization, UserAccount account) {
        initComponents();
        this.jPanel = jPanel2;
        this.organization = organization;
        this.account = account;
        populateWorkRequests();
        populateAccountRequests();
    }
    
    public void populateWorkRequests(){
        DefaultTableModel model = (DefaultTableModel)RequestsTable.getModel();
        model.setRowCount(0);
        
        for(WorkRequest request: organization.getWorkQueue().getWorkRequestList()){
            Object []row = new Object[4];
            
            if(request instanceof PrescribeMedsWorkRequest){
                
                PrescribeMedsWorkRequest medRequest = (PrescribeMedsWorkRequest) request;
                
                row[0] = medRequest;
                row[1] = medRequest.getHomeless().getFirstName()+medRequest.getHomeless().getLastName();
                row[2] = medRequest.getTestStatus();
            }
            else if(request instanceof LabTestWorkRequest){
                LabTestWorkRequest labRequest = (LabTestWorkRequest) request;
                row[0] = labRequest;
                row[1] = labRequest.getHomeless().getFirstName()+labRequest.getHomeless().getLastName();
                row[3] = labRequest.getTestStatus();
            }
            
            model.addRow(row);
        }
    }
    
    public void populateAccountRequests(){
        DefaultTableModel model = (DefaultTableModel)ResolvedTable.getModel();
        model.setRowCount(0);
        
        for(WorkRequest request: account.getWorkQueue().getWorkRequestList()){
            Object []row = new Object[4];
            
            if(request instanceof PrescribeMedsWorkRequest){
                
                PrescribeMedsWorkRequest medRequest = (PrescribeMedsWorkRequest) request;
                row[0] = medRequest;
                row[1] = medRequest.getHomeless().getFirstName()+medRequest.getHomeless().getLastName();
                row[2] = medRequest.getTestStatus();
            }
            else if(request instanceof LabTestWorkRequest){
                LabTestWorkRequest labRequest = (LabTestWorkRequest) request;
                row[0] = labRequest;
                row[1] = labRequest.getHomeless().getFirstName()+labRequest.getHomeless().getLastName();
                row[2] = labRequest.getTestStatus();
            }
            else if(request instanceof SupplyDrugsWorkRequest){
                break;
            }
            
            model.addRow(row);
        }
    }
    
    public WorkRequest getSelectedRecord(){
        if(RequestsTable.getSelectedRow()== -1){
            return null;
        }
        return (WorkRequest)RequestsTable.getValueAt(RequestsTable.getSelectedRow(),0);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ResolvedTable = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        RequestsTable = new javax.swing.JTable();

        jPanel2.setBackground(new java.awt.Color(120, 168, 252));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nurse's Work Area");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 23, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Enterprise Name:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 59, -1, -1));

        ResolvedTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Patient ID", "Patient Name", "Status"
            }
        ));
        jScrollPane1.setViewportView(ResolvedTable);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 282, 520, 99));

        RequestsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Patient ID", "Patient Name", "Prescription Status", "Test Status"
            }
        ));
        jScrollPane2.setViewportView(RequestsTable);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 102, 520, 99));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 584, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable RequestsTable;
    private javax.swing.JTable ResolvedTable;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
