/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.NurseRole;

import Business.Drug.Drug;
import Business.Enterprise.Enterprise;
import Business.Enterprise.HelpCenterEnterprise;
import Business.Homeless.HomelessIndividual;
import Business.WorkRequest.LabTestWorkRequest;
import Business.WorkRequest.PrescribeMedsWorkRequest;
import Business.WorkRequest.WorkRequest;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Yash Lekhwani
 */
public class PrescribeMedicines extends javax.swing.JPanel {
     JPanel jPanel2;
     HelpCenterEnterprise enterprise;
     LabTestWorkRequest medRequest;
     HomelessIndividual homeless;
    /**
     * Creates new form PrescribeMedicines
     */

    public PrescribeMedicines(JPanel jPanel2, HelpCenterEnterprise enterprise, WorkRequest request) {
        initComponents();
        this.jPanel2 = jPanel2;
        this.enterprise = enterprise;
        if(request instanceof LabTestWorkRequest){
            this.medRequest = (LabTestWorkRequest)request; 
            this.homeless = medRequest.getHomeless();
            WorkRequest.WorkStatusType type = WorkRequest.WorkStatusType.Accepted;
            this.medRequest.setTestStatus(type.getValue());
        }
        setFields();
        populatePrescriptionTable();
    }
    
    private void setFields(){
        patientIdTxtField.setText(String.valueOf(homeless.getId()));
        patientNameTxtField.setText(homeless.getFirstName()+" "+homeless.getLastName());
        patientIdTxtField.setEnabled(false);
        patientNameTxtField.setEnabled(false);
    }
    
    private void populatePrescriptionTable(){
        DefaultTableModel model = (DefaultTableModel)prescriptionTbl.getModel();
        model.setRowCount(0);
        Object []row = new Object[3];
        for(String drugName: medRequest.getPrescription().keySet()){
            for(Drug drug: enterprise.getDrugList().values()){
                if(drug.getName().equals(drugName)){
                    row[0] = drug;
                    row[1] = drugName;
                    row[2] = medRequest.getPrescription().get(drugName);
                    model.addRow(row);
                    break;
                }
            }
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        patientIdTxtField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        patientNameTxtField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        prescriptionTbl = new javax.swing.JTable();
        fulfillBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(120, 168, 252));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Patient Id:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(112, 85, -1, -1));

        patientIdTxtField.setEditable(false);
        add(patientIdTxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(271, 84, 223, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Patient Name:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(112, 136, -1, -1));

        patientNameTxtField.setEditable(false);
        patientNameTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                patientNameTxtFieldActionPerformed(evt);
            }
        });
        add(patientNameTxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(271, 135, 223, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Prescription");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(283, 195, -1, -1));

        prescriptionTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Drug Id", "Drug Name", "Quantity"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(prescriptionTbl);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(112, 233, -1, 148));

        fulfillBtn.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        fulfillBtn.setText("Fulfill");
        fulfillBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fulfillBtnActionPerformed(evt);
            }
        });
        add(fulfillBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(487, 399, -1, -1));

        backBtn.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        backBtn.setText("< Back");
        add(backBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(112, 399, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Prescribe Medicines");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(256, 27, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void patientNameTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_patientNameTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_patientNameTxtFieldActionPerformed

    private void fulfillBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fulfillBtnActionPerformed
        // TODO add your handling code here:
        int drugId = ((Drug)prescriptionTbl.getValueAt(prescriptionTbl.getSelectedRow(), 0)).getId();
        String drugName = String.valueOf(prescriptionTbl.getValueAt(prescriptionTbl.getSelectedRow(), 1));
        int quantity = (Integer)prescriptionTbl.getValueAt(prescriptionTbl.getSelectedRow(), 2);
        
        for(Drug drug: enterprise.getDrugList().values()){
            if(drug.getId()==drugId){
                if(quantity<=drug.getQuantity()){
                    medRequest.getPrescription().remove(drugName);
                    populatePrescriptionTable();
                    int quant = (drug.getQuantity() - quantity) > 0 ? drug.getQuantity()-quantity: 0;
                    drug.setQuantity(quant);
                }else{
                    JOptionPane.showMessageDialog(null, "Inventory low");
                }
            }
        }
        if(prescriptionTbl.getRowCount()==0){
            JOptionPane.showMessageDialog(null, "Prescription complete");
            WorkRequest.WorkStatusType type = WorkRequest.WorkStatusType.Completed;
            medRequest.setTestStatus(type.getValue());
        }
    }//GEN-LAST:event_fulfillBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JButton fulfillBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField patientIdTxtField;
    private javax.swing.JTextField patientNameTxtField;
    private javax.swing.JTable prescriptionTbl;
    // End of variables declaration//GEN-END:variables
}
