/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.SysAdminRole;

import Business.Enterprise.Enterprise;
import Business.Network.Network;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import Business.EcoSystem;
import java.awt.CardLayout;
import java.io.IOException;
import java.text.ParseException;

import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.JPanel;

/**
 *
 * @author Varada
 */
public class ManageEnterpriseJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageEnterpriseJPanel
     */
    JPanel jPanel2;
    EcoSystem ecosystem;
    public ManageEnterpriseJPanel(JPanel jPanel2, EcoSystem ecosystem) {
        initComponents();
        
        this.ecosystem=ecosystem;
        this.jPanel2=jPanel2;
        populateTable();
        populateComboBox();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        enterpriseJTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        networkComboBox = new javax.swing.JComboBox();
        enterpriseTypeComboBox = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        nameOfEnterpriseTxtField = new javax.swing.JTextField();
        addEnterpriseBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(120, 168, 252));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        enterpriseJTable.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        enterpriseJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Enterprise Name", "Network", "Type of Enterprise"
            }
        ));
        jScrollPane1.setViewportView(enterpriseJTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 58, 391, 99));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Network:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 178, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Enterprise Type:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 235, -1, -1));

        networkComboBox.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        networkComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        networkComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                networkComboBoxActionPerformed(evt);
            }
        });
        add(networkComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(266, 175, -1, -1));

        enterpriseTypeComboBox.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        enterpriseTypeComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(enterpriseTypeComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(266, 229, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Name of Enterprise:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 287, -1, -1));
        add(nameOfEnterpriseTxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(266, 291, 78, -1));

        nameOfEnterpriseTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameOfEnterpriseTxtFieldActionPerformed(evt);
            }
        });

        addEnterpriseBtn.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        addEnterpriseBtn.setText("Add Enterprise");
        addEnterpriseBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addEnterpriseBtnActionPerformed(evt);
            }
        });
        add(addEnterpriseBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(238, 322, -1, -1));

        backBtn.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        backBtn.setText("Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        add(backBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 322, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Manage Enterprise Admin");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(172, 15, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void networkComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_networkComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_networkComboBoxActionPerformed
    
    private void populateTable() {
        DefaultTableModel model = (DefaultTableModel) enterpriseJTable.getModel();

        model.setRowCount(0);
        for (Network network : ecosystem.getNetworkList()) {
            for (Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()) {
                Object[] row = new Object[3];
                row[0] = enterprise.getName();
                row[1] = network.getName();
                row[2] = enterprise.getEnterpriseType().getValue();

                model.addRow(row);
            }
        }
    }
    
    private void populateComboBox() {
        networkComboBox.removeAllItems();
        enterpriseTypeComboBox.removeAllItems();

        for (Network network : ecosystem.getNetworkList()) {
            networkComboBox.addItem(network);
        }

        for (Enterprise.EnterpriseType type : Enterprise.EnterpriseType.values()) {
            enterpriseTypeComboBox.addItem(type);
        }

    }
        
    private void addEnterpriseBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addEnterpriseBtnActionPerformed
        Network network = (Network)networkComboBox.getSelectedItem();
        Enterprise.EnterpriseType enterpriseType = (Enterprise.EnterpriseType)enterpriseTypeComboBox.getSelectedItem();
        
        if (network == null || enterpriseType == null) {
            JOptionPane.showMessageDialog(null, "Invalid Input!");
            return;
        }
        
        String enterpriseName = nameOfEnterpriseTxtField.getText();
        

         try{network.getEnterpriseDirectory().createAndAddEnterprise(enterpriseName, enterpriseType);}
         catch(Exception e){
             System.out.println(e);
         }
        populateTable();
    }//GEN-LAST:event_addEnterpriseBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        jPanel2.remove(this);
        CardLayout layout = (CardLayout)jPanel2.getLayout();
        layout.previous(jPanel2);
                                 
    }//GEN-LAST:event_backBtnActionPerformed

    private void nameOfEnterpriseTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameOfEnterpriseTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameOfEnterpriseTxtFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addEnterpriseBtn;
    private javax.swing.JButton backBtn;
    private javax.swing.JTable enterpriseJTable;
    private javax.swing.JComboBox enterpriseTypeComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nameOfEnterpriseTxtField;
    private javax.swing.JComboBox networkComboBox;
    // End of variables declaration//GEN-END:variables
}
