/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.SysAdminRole;

import Business.EcoSystem;
import Business.Network.Network;
import java.awt.CardLayout;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Varada
 */
public class ManageNetworkJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageNetworkJPanel
     */
    JPanel jPanel2;
    EcoSystem ecosystem;
    public ManageNetworkJPanel(JPanel jPanel2, EcoSystem ecosystem) {
        initComponents();
        this.ecosystem=ecosystem;
        this.jPanel2=jPanel2;
        
        populateNetworkTable();
    }
    
    private void populateNetworkTable() {
        DefaultTableModel model = (DefaultTableModel) networkTbl.getModel();

        model.setRowCount(0);
        for (Network network : ecosystem.getNetworkList()) {
            Object[] row = new Object[1];
            row[0] = network.getName();
            model.addRow(row);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        networkTbl = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        networkNameTxtField = new javax.swing.JTextField();
        addNetworkBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(120, 168, 252));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        networkTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Name"
            }
        ));
        jScrollPane2.setViewportView(networkTbl);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(114, 104, 334, 91));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Name of Network:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(114, 217, -1, -1));

        networkNameTxtField.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        networkNameTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                networkNameTxtFieldActionPerformed(evt);
            }
        });
        add(networkNameTxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(272, 214, 105, -1));

        addNetworkBtn.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        addNetworkBtn.setText("Add");
        addNetworkBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addNetworkBtnActionPerformed(evt);
            }
        });
        add(addNetworkBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(395, 213, -1, -1));

        backBtn.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        backBtn.setText("Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        add(backBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(114, 312, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Manage Network");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(208, 47, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void networkNameTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_networkNameTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_networkNameTxtFieldActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        jPanel2.remove(this);
        CardLayout layout = (CardLayout)jPanel2.getLayout();
        layout.previous(jPanel2);
    }//GEN-LAST:event_backBtnActionPerformed

    private void addNetworkBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addNetworkBtnActionPerformed
        // TODO add your handling code here:
        String networkName = networkNameTxtField.getText();
        ecosystem.createAndAddNetwork().setName(networkName);
        populateNetworkTable();
    }//GEN-LAST:event_addNetworkBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addNetworkBtn;
    private javax.swing.JButton backBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField networkNameTxtField;
    private javax.swing.JTable networkTbl;
    // End of variables declaration//GEN-END:variables
}
