/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.SysAdminRole;

import Business.DB4OUtil.DB4OUtil;
import Business.EcoSystem;
import java.awt.CardLayout;
import javax.swing.JPanel;
import javax.swing.JSplitPane;

/**
 *
 * @author Varada
 */
public class SystemAdminWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form SystemAdminWorkAreaJPanel
     */
    private DB4OUtil dB4OUtil = DB4OUtil.getInstance();
    EcoSystem ecosystem;
    JPanel jPanel;
    public SystemAdminWorkAreaJPanel(JPanel jPanel1, EcoSystem ecosystem) {
        initComponents();
        this.ecosystem=ecosystem;
        this.jPanel = jPanel1;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        manageNetworkLbl = new javax.swing.JLabel();
        manageEnterpriseLbl = new javax.swing.JLabel();
        manageEnterpriseAdminLbl = new javax.swing.JLabel();
        logout = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();

        jPanel1.setBackground(new java.awt.Color(71, 120, 197));

        manageNetworkLbl.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        manageNetworkLbl.setForeground(new java.awt.Color(255, 255, 255));
        manageNetworkLbl.setText("Manage Network");
        manageNetworkLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                manageNetworkLblMouseClicked(evt);
            }
        });

        manageEnterpriseLbl.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        manageEnterpriseLbl.setForeground(new java.awt.Color(255, 255, 255));
        manageEnterpriseLbl.setText("Manage Enterprise");
        manageEnterpriseLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                manageEnterpriseLblMouseClicked(evt);
            }
        });

        manageEnterpriseAdminLbl.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        manageEnterpriseAdminLbl.setForeground(new java.awt.Color(255, 255, 255));
        manageEnterpriseAdminLbl.setText("Manage Enterprise Admin");
        manageEnterpriseAdminLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                manageEnterpriseAdminLblMouseClicked(evt);
            }
        });

        logout.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        logout.setText("LOGOUT");
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(manageNetworkLbl)
                    .addComponent(manageEnterpriseLbl)
                    .addComponent(manageEnterpriseAdminLbl)
                    .addComponent(logout))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(manageNetworkLbl)
                .addGap(27, 27, 27)
                .addComponent(manageEnterpriseLbl)
                .addGap(27, 27, 27)
                .addComponent(manageEnterpriseAdminLbl)
                .addGap(27, 27, 27)
                .addComponent(logout)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jSplitPane1.setLeftComponent(jPanel1);

        jPanel2.setBackground(new java.awt.Color(120, 168, 252));
        jPanel2.setLayout(new java.awt.CardLayout());
        jSplitPane1.setRightComponent(jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void manageNetworkLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manageNetworkLblMouseClicked
        // TODO add your handling code here:
        ManageNetworkJPanel mnp = new ManageNetworkJPanel(jPanel2, ecosystem);
        jPanel2.add("ManageNetworkJPanel", mnp);
        CardLayout layout = (CardLayout)jPanel2.getLayout();
        layout.next(jPanel2);
       
    }//GEN-LAST:event_manageNetworkLblMouseClicked

    private void manageEnterpriseLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manageEnterpriseLblMouseClicked
        // TODO add your handling code here:
        ManageEnterpriseJPanel mep = new ManageEnterpriseJPanel(jPanel2, ecosystem);
        jPanel2.add("ManageEnterpriseJPanel", mep);
        CardLayout layout = (CardLayout)jPanel2.getLayout();
        layout.next(jPanel2);
    }//GEN-LAST:event_manageEnterpriseLblMouseClicked

    private void manageEnterpriseAdminLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manageEnterpriseAdminLblMouseClicked
        // TODO add your handling code here:
        ManageEnterpriseAdminJPanel meap = new ManageEnterpriseAdminJPanel(jPanel2, ecosystem);
        jPanel2.add("ManageEnterpriseAdminJPanel",meap);
        CardLayout layout = (CardLayout)jPanel2.getLayout();
        layout.next(jPanel2);
    }//GEN-LAST:event_manageEnterpriseAdminLblMouseClicked

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        // TODO add your handling code here:
        jPanel.remove(this);
        CardLayout layout = (CardLayout)jPanel.getLayout();
        layout.previous(jPanel);
        dB4OUtil.storeSystem(ecosystem);
    }//GEN-LAST:event_logoutActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JButton logout;
    private javax.swing.JLabel manageEnterpriseAdminLbl;
    private javax.swing.JLabel manageEnterpriseLbl;
    private javax.swing.JLabel manageNetworkLbl;
    // End of variables declaration//GEN-END:variables
}

