/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.StockerRole;

import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.WorkRequest.ReceptionistWorkRequest;
import Business.WorkRequest.StockerWorkRequest;
import Business.WorkRequest.WorkRequest;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Varada
 */
public class StockerHomeJPanel extends javax.swing.JPanel {

    /**
     * Creates new form StockerHomeJPanel
     */
    Organization org;
    UserAccount account;
    JPanel jpanel1;   
    public StockerHomeJPanel(JPanel jPanel2, UserAccount account, Organization org) {
        initComponents();
        this.jpanel1=jPanel2;
        this.account=account;
        this.org=org;
        populateFoodRequest();
        populateLogTable();
    }
    
    public void populateFoodRequest(){
        DefaultTableModel dtm = (DefaultTableModel)foodReqTbl.getModel();
        dtm.setRowCount(0);
        
        for(WorkRequest workRequest :org.getWorkQueue().getWorkRequestList()){
            Object []row = new Object[3];
            row[0] = workRequest;
            row[1] = workRequest.getHomeless().getFirstName() +" " + workRequest.getHomeless().getLastName();
            row[2] = workRequest.getMessage();
            dtm.addRow(row);
        }
    }
    
    public void populateLogTable(){
        DefaultTableModel dtm = (DefaultTableModel)logTbl.getModel();
        dtm.setRowCount(0);
        
        for(WorkRequest req : account.getWorkQueue().getWorkRequestList()){
            Object []row = new Object[3];
            
            if(req instanceof StockerWorkRequest){
                StockerWorkRequest foodRequest = (StockerWorkRequest) req;
                
                row[0] = foodRequest;
                //row[1] = foodRequest.getHomeless().getFirstName() + " " + foodRequest.getHomeless().getLastName();
                row[2] = foodRequest.getStatus();
                dtm.addRow(row);
                
            }
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    public Object getSelectedIndividual(){
        if(foodReqTbl.getSelectedRow()<0){
            return null;
        }
        return foodReqTbl.getValueAt(foodReqTbl.getSelectedRow(), 0);
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        foodReqTbl = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        logTbl = new javax.swing.JTable();

        setBackground(new java.awt.Color(120, 168, 252));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Stocker Work Area");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(211, 16, -1, -1));

        foodReqTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Person ID", "Person Name", "Message"
            }
        ));
        jScrollPane1.setViewportView(foodReqTbl);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(157, 76, 308, 92));

        logTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Person ID", "Person Name", "Status"
            }
        ));
        jScrollPane2.setViewportView(logTbl);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(157, 237, 308, 97));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable foodReqTbl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable logTbl;
    // End of variables declaration//GEN-END:variables
}
