/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.StockerRole;

import Business.DB4OUtil.DB4OUtil;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;

import Business.Enterprise.FoodEnterprise;

import Business.Enterprise.HelpCenterEnterprise;
import Business.Homeless.HomelessIndividual;
import Business.Organization.Organization;
import Business.Organization.StockerOrganization;
import Business.UserAccount.UserAccount;
import Business.WorkRequest.WorkRequest;
import java.awt.CardLayout;
import javax.swing.JOptionPane;

import javax.swing.JPanel;

/**
 *
 * @author Yash Lekhwani
 */
public class StockerWorkAreaJPanel extends javax.swing.JPanel {
  


    
    HelpCenterEnterprise helpCenterEnterprise;
    EcoSystem business;
    UserAccount account;
    JPanel jpanel;
    private DB4OUtil db4outil = DB4OUtil.getInstance();
    Organization org;
    StockerHomeJPanel shjp;
    public StockerWorkAreaJPanel(JPanel jpanel,  HelpCenterEnterprise helpCenterEnterprise, UserAccount account, EcoSystem business) {
        initComponents();
        this.jpanel=jpanel;
        this.business=business;
        this.account  = account;
        this.helpCenterEnterprise=helpCenterEnterprise;
        for(Organization org : helpCenterEnterprise.getOrganizationDirectory().getOrganizationList()){
            if(org instanceof StockerOrganization)
                this.org=org;
            
        }
        this.shjp = new StockerHomeJPanel(jPanel2, account, org);
        jPanel2.add("StockerHomeJPanel", shjp);
        CardLayout layout = (CardLayout)jPanel2.getLayout();
        layout.next(jPanel2);  

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private HomelessIndividual retrieveIndividual(){
        if(shjp.getSelectedIndividual() == null){
            return null;
        }
        WorkRequest request;
        request = (WorkRequest)shjp.getSelectedIndividual();
        HomelessIndividual homeless = request.getHomeless();
        return homeless;
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        serviceFoodLbl = new javax.swing.JLabel();
        logoutBtn = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();

        jSplitPane1.setDividerLocation(220);

        jPanel1.setBackground(new java.awt.Color(71, 120, 197));

        serviceFoodLbl.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        serviceFoodLbl.setForeground(new java.awt.Color(255, 255, 255));
        serviceFoodLbl.setText("Service Food");
        serviceFoodLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                serviceFoodLblMouseClicked(evt);
            }
        });

        logoutBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        logoutBtn.setText("Logout");
        logoutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(serviceFoodLbl)
                    .addComponent(logoutBtn))
                .addContainerGap(80, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(148, 148, 148)
                .addComponent(serviceFoodLbl)
                .addGap(106, 106, 106)
                .addComponent(logoutBtn)
                .addContainerGap(306, Short.MAX_VALUE))
        );

        jSplitPane1.setLeftComponent(jPanel1);

        jPanel2.setBackground(new java.awt.Color(120, 168, 252));
        jPanel2.setLayout(new java.awt.CardLayout());
        jSplitPane1.setRightComponent(jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jSplitPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 868, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jSplitPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 620, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void serviceFoodLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_serviceFoodLblMouseClicked
        // TODO add your handling code here:
        if(this.retrieveIndividual() == null){
            JOptionPane.showMessageDialog(null, "Please select a row");
            return;
        }
        ServiceFoodJPanel sfjp = new ServiceFoodJPanel(shjp, jPanel2, helpCenterEnterprise, account, this.retrieveIndividual());
        jPanel2.add("ServiceFoodJPanel", sfjp);
        CardLayout layout = (CardLayout)jPanel2.getLayout();
        layout.next(jPanel2);
    }//GEN-LAST:event_serviceFoodLblMouseClicked

    private void logoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutBtnActionPerformed
        // TODO add your handling code here:
        jpanel.remove(this);
        CardLayout layout = (CardLayout)jpanel.getLayout();
        layout.previous(jpanel);
        db4outil.storeSystem(business);
    }//GEN-LAST:event_logoutBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JButton logoutBtn;
    private javax.swing.JLabel serviceFoodLbl;
    // End of variables declaration//GEN-END:variables
}
