/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.RelationsManagerRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Enterprise.HelpCenterEnterprise;
import Business.Enterprise.HospitalEnterprise;
import Business.Network.Network;
import Business.Organization.Organization;
import Business.Organization.RelationManagerOrganization;
import Business.UserAccount.UserAccount;
import Business.WorkRequest.LabTestWorkRequest;
import Business.WorkRequest.SupplyDrugsWorkRequest;
import Business.WorkRequest.WorkRequest;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author amans
 */
public class RelationsManagerRequestsJPanel extends javax.swing.JPanel {

    /**
     * Creates new form RelationsManagerHomeJPanel
     */
    JPanel jpanel;
    HelpCenterEnterprise enterprise;
    UserAccount account;
    EcoSystem system; 
    RelationManagerOrganization organization = null;
    public RelationsManagerRequestsJPanel(JPanel jpanel, HelpCenterEnterprise enterprise, UserAccount account, EcoSystem system) {
        initComponents();
        this.jpanel = jpanel;
        this.enterprise = enterprise;
        this.account = account;
        this.system = system;
        populateRequestsTable();
    }
    
    private void populateRequestsTable(){
        DefaultTableModel model = (DefaultTableModel)requestsTbl.getModel();
        model.setRowCount(0);
        Object []row = new Object[4];
        for(Organization org: enterprise.getOrganizationDirectory().getOrganizationList()){
            if(org instanceof RelationManagerOrganization){
                organization = (RelationManagerOrganization)org;
            }
        }
        for(WorkRequest request: organization.getWorkQueue().getWorkRequestList()){
            if(requestTypeComboBox.getSelectedItem().toString() == "Supply Drugs Requests" && (request instanceof SupplyDrugsWorkRequest)){
                row[0] = request;
                row[1] = request.getSender();
                row[2] = request.getRequestDate();
                row[3] = WorkRequest.WorkStatusType.Pending.getValue();
                model.addRow(row);
            }else if(requestTypeComboBox.getSelectedItem().toString() == "Lab Test Requests" && (request instanceof LabTestWorkRequest)){
                row[0] = request;
                row[1] = request.getSender();
                row[2] = request.getRequestDate();
                row[3] = WorkRequest.WorkStatusType.Pending.getValue();
                model.addRow(row);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        requestsTbl = new javax.swing.JTable();
        publishBtn = new javax.swing.JButton();
        requestTypeComboBox = new javax.swing.JComboBox<String>();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(120, 168, 252));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        requestsTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Request Id", "Sender", "Request Date", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(requestsTbl);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(145, 127, -1, 270));

        publishBtn.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        publishBtn.setText("Publish Requests");
        publishBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                publishBtnActionPerformed(evt);
            }
        });
        add(publishBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(446, 438, -1, -1));

        requestTypeComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Supply Drugs Requests", "Lab Test Requests" }));
        requestTypeComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                requestTypeComboBoxItemStateChanged(evt);
            }
        });
        add(requestTypeComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 72, 287, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Request Type:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 71, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void publishBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_publishBtnActionPerformed
        // TODO add your handling code here:
        for(Network network: system.getNetworkList()){
            for(Enterprise enterprise: network.getEnterpriseDirectory().getEnterpriseList()){
                if(this.enterprise == enterprise){
                        for(Enterprise ent: network.getEnterpriseDirectory().getEnterpriseList()){
                            if(ent instanceof HospitalEnterprise){
                                for(int i=0;i<requestsTbl.getRowCount();i++){
                                    ent.getWorkQueue().getWorkRequestList().add((WorkRequest)requestsTbl.getValueAt(i, 0));
                                    this.organization.getWorkQueue().getWorkRequestList().remove((WorkRequest)requestsTbl.getValueAt(i, 0));
                                }
                                DefaultTableModel model = (DefaultTableModel)requestsTbl.getModel();
                                model.setRowCount(0);
                                break;
                            }
                        }
                        break;
                }
                break;
            }
        }
    }//GEN-LAST:event_publishBtnActionPerformed

    private void requestTypeComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_requestTypeComboBoxItemStateChanged
        // TODO add your handling code here:
        populateRequestsTable();
    }//GEN-LAST:event_requestTypeComboBoxItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton publishBtn;
    private javax.swing.JComboBox<String> requestTypeComboBox;
    private javax.swing.JTable requestsTbl;
    // End of variables declaration//GEN-END:variables
}
