/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.RelationsManagerRole;

import Business.DB4OUtil.DB4OUtil;
import Business.EcoSystem;
import Business.Enterprise.HelpCenterEnterprise;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author amans
 */
public class RelationsManagerWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form RelationsManagerWorkAreaJPanel
     */
    JPanel jpanel;
    EcoSystem system;
    HelpCenterEnterprise enterprise;
    UserAccount account;
    RelationsManagerRequestsJPanel rmrjp;
    private DB4OUtil dB4OUtil = DB4OUtil.getInstance();
    public RelationsManagerWorkAreaJPanel(JPanel jpanel, EcoSystem ecosystem, HelpCenterEnterprise enterprise, UserAccount account) {
        initComponents();
        this.jpanel = jpanel;
        this.system = ecosystem;
        this.enterprise = enterprise;
        this.account = account;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        Logout = new javax.swing.JButton();
        DrugRequestLbl = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();

        jSplitPane1.setDividerLocation(220);

        jPanel1.setBackground(new java.awt.Color(71, 120, 197));

        Logout.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Logout.setText("LOGOUT");
        Logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutActionPerformed(evt);
            }
        });

        DrugRequestLbl.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        DrugRequestLbl.setForeground(new java.awt.Color(255, 255, 255));
        DrugRequestLbl.setText("View Requests");
        DrugRequestLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DrugRequestLblMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(Logout)
                .addContainerGap(69, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(DrugRequestLbl)
                .addGap(44, 44, 44))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(168, 168, 168)
                .addComponent(DrugRequestLbl)
                .addGap(88, 88, 88)
                .addComponent(Logout)
                .addContainerGap(262, Short.MAX_VALUE))
        );

        jSplitPane1.setLeftComponent(jPanel1);

        jPanel2.setBackground(new java.awt.Color(120, 168, 252));
        jPanel2.setLayout(new java.awt.CardLayout());
        jSplitPane1.setRightComponent(jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 623, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void LogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutActionPerformed
        // TODO add your handling code here:
        jpanel.remove(this);
        CardLayout layout = (CardLayout)jpanel.getLayout();
        layout.previous(jpanel);
        dB4OUtil.storeSystem(system);
    }//GEN-LAST:event_LogoutActionPerformed

    private void DrugRequestLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DrugRequestLblMouseClicked
        // TODO add your handling code here:
        this.rmrjp = new RelationsManagerRequestsJPanel(jPanel2, enterprise, account, system);
        jPanel2.add("RelationsManagerRequestJPanel", rmrjp);
        CardLayout layout = (CardLayout)jPanel2.getLayout();
        layout.next(jPanel2);
    }//GEN-LAST:event_DrugRequestLblMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DrugRequestLbl;
    private javax.swing.JButton Logout;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSplitPane jSplitPane1;
    // End of variables declaration//GEN-END:variables
}
