/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.ShelterHomeManagerRole;

import Business.DB4OUtil.DB4OUtil;
import Business.EcoSystem;
import Business.Enterprise.ShelterHomeEnterprise;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author amans
 */
public class ShelterHomeManagerWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ShelterHomeManagerWorkAreaJPanel
     */
    private JPanel jpanel;
    private EcoSystem system;
    private UserAccount account;
    private ShelterHomeEnterprise enterprise;
    private DB4OUtil dB4OUtil = DB4OUtil.getInstance();
    public ShelterHomeManagerWorkAreaJPanel(JPanel jpanel, EcoSystem system, UserAccount account, ShelterHomeEnterprise enterprise) {
        initComponents();
        this.jpanel = jpanel;
        this.system = system;
        this.account = account;
        this.enterprise = enterprise;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        logoutLbl = new javax.swing.JButton();
        addPropertyLbl = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();

        setBackground(new java.awt.Color(120, 168, 252));

        jSplitPane1.setDividerLocation(220);

        jPanel1.setBackground(new java.awt.Color(71, 120, 197));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logoutLbl.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        logoutLbl.setText("Logout");
        logoutLbl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutLblActionPerformed(evt);
            }
        });
        jPanel1.add(logoutLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 137, -1, -1));

        addPropertyLbl.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        addPropertyLbl.setForeground(new java.awt.Color(255, 255, 255));
        addPropertyLbl.setText("Add New Property");
        addPropertyLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addPropertyLblMouseClicked(evt);
            }
        });
        jPanel1.add(addPropertyLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 79, -1, -1));

        jSplitPane1.setLeftComponent(jPanel1);

        jPanel2.setBackground(new java.awt.Color(120, 168, 252));
        jPanel2.setLayout(new java.awt.CardLayout());
        jSplitPane1.setRightComponent(jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void logoutLblActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutLblActionPerformed
        // TODO add your handling code here:
        jpanel.remove(this);
        CardLayout layout = (CardLayout)jpanel.getLayout();
        layout.previous(jpanel);
        dB4OUtil.storeSystem(system);
    }//GEN-LAST:event_logoutLblActionPerformed

    private void addPropertyLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addPropertyLblMouseClicked
        // TODO add your handling code here:
        ShelterHomeManagerHomeJPanel shmhjp = new ShelterHomeManagerHomeJPanel(jPanel2, account, enterprise, system);
        jPanel2.add("Shelter Manager Home", shmhjp);
        CardLayout layout = (CardLayout)jPanel2.getLayout();
        layout.next(jPanel2);
    }//GEN-LAST:event_addPropertyLblMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addPropertyLbl;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JButton logoutLbl;
    // End of variables declaration//GEN-END:variables
}
