/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.ShelterHomeManagerRole;

import Business.Accomodation.Accomodation;
import Business.Accomodation.AccomodationDirectory;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Enterprise.HelpCenterEnterprise;
import Business.Enterprise.ShelterHomeEnterprise;
import Business.Network.Network;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author amans
 */
public class ShelterHomeManagerHomeJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ShelterHomeManagerHomeJPanel
     */
    private JPanel jpanel;
    private UserAccount account;
    private ShelterHomeEnterprise enterprise;
    private EcoSystem system;
    public ShelterHomeManagerHomeJPanel(JPanel jpanel, UserAccount account, ShelterHomeEnterprise enterprise, EcoSystem system) {
        initComponents();
        this.jpanel = jpanel;
        this.account = account;
        this.enterprise = enterprise;
        this.system = system;
        populateAccoTbl();
        publishChanges();
    }

    private void populateAccoTbl(){
        DefaultTableModel model = (DefaultTableModel)accoTbl.getModel();
        model.setRowCount(0);
        Object row[] = new Object[3];
        
        for(Accomodation acco: enterprise.getAccomodationDirectory().getAccomodationDirectory()){
            row[0] = acco;
            row[1] = acco.getLocation();
            row[2] = acco.getNoOfSpots();
            model.addRow(row);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        accoNameTxtField = new javax.swing.JTextField();
        accoLocationTxtField = new javax.swing.JTextField();
        spotsTxtField = new javax.swing.JTextField();
        addAccoBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        accoTbl = new javax.swing.JTable();
        unpublishAccoBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(120, 168, 252));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Accomodation Name:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(189, 95, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Accomodation Location:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(189, 140, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("No. of Spots:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(189, 185, -1, -1));
        add(accoNameTxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 96, 236, -1));
        add(accoLocationTxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 141, 236, -1));
        add(spotsTxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 186, 236, -1));

        addAccoBtn.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        addAccoBtn.setText("Publish Accommodation");
        addAccoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addAccoBtnActionPerformed(evt);
            }
        });
        add(addAccoBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(483, 243, -1, -1));

        backBtn.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        backBtn.setText("Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        add(backBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 490, -1, -1));

        accoTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Location", "Spots"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        accoTbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                accoTblMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(accoTbl);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(189, 290, 497, 184));

        unpublishAccoBtn.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        unpublishAccoBtn.setText("Unpublish Accommodation");
        unpublishAccoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unpublishAccoBtnActionPerformed(evt);
            }
        });
        add(unpublishAccoBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(463, 483, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void addAccoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addAccoBtnActionPerformed
        // TODO add your handling code here:
        String accoName = accoNameTxtField.getText();
        String accoLocation = accoLocationTxtField.getText();
        int spots = Integer.parseInt(spotsTxtField.getText());
        ArrayList<Accomodation> accoDirect = enterprise.getAccomodationDirectory().getAccomodationDirectory();
        for(Accomodation acco: accoDirect){
            if(acco.getAccomodationName()==accoName && acco.getLocation()==accoLocation){
                acco.setNoOfSpots(acco.getNoOfSpots()+spots);
            }else{
                Accomodation accomodation = new Accomodation(accoName,  accoLocation, spots);
                enterprise.getAccomodationDirectory().getAccomodationDirectory().add(accomodation);
            }
            populateAccoTbl();
        }
        publishChanges();
    }//GEN-LAST:event_addAccoBtnActionPerformed
    private void publishChanges(){
        for(Network net: system.getNetworkList()){
            for(Enterprise ent: net.getEnterpriseDirectory().getEnterpriseList()){
                if(ent.getEnterpriseType().equals(Enterprise.EnterpriseType.HelpCenter)){
                    HelpCenterEnterprise helpcenter = (HelpCenterEnterprise)ent;
                    for(Accomodation acco: enterprise.getAccomodationDirectory().getAccomodationDirectory()){
                                if(helpcenter.getAccomodationDirectory().getAccomodationDirectory().indexOf(acco)== -1)
                                helpcenter.getAccomodationDirectory().getAccomodationDirectory().add(acco);
                            }
                        }
                    }
                }
            }
    private void unpublishAccoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unpublishAccoBtnActionPerformed
        // TODO add your handling code here:
        if(accoTbl.getSelectedRow()<0){
            JOptionPane.showMessageDialog(null,"Please select a row");
            return;
        }
        Accomodation acco = (Accomodation)accoTbl.getValueAt(accoTbl.getSelectedRow(), 0);
        enterprise.getAccomodationDirectory().getAccomodationDirectory().remove(acco);
        populateAccoTbl();
        publishChanges();
    }//GEN-LAST:event_unpublishAccoBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        jpanel.remove(this);
        CardLayout layout = (CardLayout)jpanel.getLayout();
        layout.previous(jpanel);
    }//GEN-LAST:event_backBtnActionPerformed

    private void accoTblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_accoTblMouseClicked
        // TODO add your handling code here:
        Accomodation acco = (Accomodation)accoTbl.getValueAt(accoTbl.getSelectedRow(), 0);
        accoNameTxtField.setText(acco.getAccomodationName());
        accoLocationTxtField.setText(acco.getLocation());
        spotsTxtField.setText(String.valueOf(acco.getNoOfSpots()));
    }//GEN-LAST:event_accoTblMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField accoLocationTxtField;
    private javax.swing.JTextField accoNameTxtField;
    private javax.swing.JTable accoTbl;
    private javax.swing.JButton addAccoBtn;
    private javax.swing.JButton backBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField spotsTxtField;
    private javax.swing.JButton unpublishAccoBtn;
    // End of variables declaration//GEN-END:variables
}
