/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.DoctorRole;

import Business.EcoSystem;
import Business.Homeless.HomelessIndividual;
import Business.Organization.DoctorOrganization;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.WorkRequest.WorkRequest;
import Business.DB4OUtil.DB4OUtil;
import Business.Enterprise.HelpCenterEnterprise;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Varada
 */
public class DoctorWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form DoctorWorkAreaJPanel
     */
    JPanel jPanel;
    HelpCenterEnterprise enterprise;
    UserAccount account;
    DoctorWorkAreaHomeJPanel dwahjp;
    Organization org;
    private DB4OUtil dB4OUtil = DB4OUtil.getInstance();
    EcoSystem system;
    public DoctorWorkAreaJPanel(JPanel jPanel, HelpCenterEnterprise enterprise, UserAccount account, EcoSystem system) {
        initComponents();
        this.jPanel=jPanel;
        this.enterprise=enterprise;
        this.account = account;
        this.system = system;
        for(Organization org : enterprise.getOrganizationDirectory().getOrganizationList()){
            if(org instanceof DoctorOrganization)
                this.org = org;
        }
        System.out.println(system);
        this.dwahjp = new DoctorWorkAreaHomeJPanel(jPanel2, org, account);
        jPanel2.add("DoctorWorkAreaHomeJPanel", dwahjp);
        CardLayout layout = (CardLayout)jPanel2.getLayout();
        layout.next(jPanel2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        precribeMedicinesLbl = new javax.swing.JLabel();
        requestTestLbl = new javax.swing.JLabel();
        logoutBtn = new javax.swing.JButton();
        viewTestLbl = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();

        jPanel1.setBackground(new java.awt.Color(71, 120, 197));

        precribeMedicinesLbl.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        precribeMedicinesLbl.setForeground(new java.awt.Color(255, 255, 255));
        precribeMedicinesLbl.setText("Prescribe Medicines");
        precribeMedicinesLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                precribeMedicinesLblMouseClicked(evt);
            }
        });

        requestTestLbl.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        requestTestLbl.setForeground(new java.awt.Color(255, 255, 255));
        requestTestLbl.setText("Request Test");
        requestTestLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                requestTestLblMouseClicked(evt);
            }
        });

        logoutBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        logoutBtn.setText("Logout");
        logoutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutBtnActionPerformed(evt);
            }
        });

        viewTestLbl.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        viewTestLbl.setForeground(new java.awt.Color(255, 255, 255));
        viewTestLbl.setText("View Test Status");
        viewTestLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                viewTestLblMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(requestTestLbl)
                    .addComponent(logoutBtn)
                    .addComponent(precribeMedicinesLbl)
                    .addComponent(viewTestLbl))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addComponent(precribeMedicinesLbl)
                .addGap(30, 30, 30)
                .addComponent(requestTestLbl)
                .addGap(30, 30, 30)
                .addComponent(viewTestLbl)
                .addGap(30, 30, 30)
                .addComponent(logoutBtn)
                .addContainerGap(264, Short.MAX_VALUE))
        );

        jSplitPane1.setLeftComponent(jPanel1);

        jPanel2.setBackground(new java.awt.Color(120, 168, 252));
        jPanel2.setLayout(new java.awt.CardLayout());
        jSplitPane1.setRightComponent(jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 613, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void precribeMedicinesLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_precribeMedicinesLblMouseClicked
        // TODO add your handling code here:
        WorkRequest request = null;
        if(dwahjp.getSelectedPatient()!=null){
            request = (WorkRequest)dwahjp.getSelectedPatient();
        }else if(dwahjp.getLabTestRequest().getTestStatus().equals(WorkRequest.WorkStatusType.Processed.getValue())){
            request = (WorkRequest)dwahjp.getLabTestRequest();
        }else{
            JOptionPane.showMessageDialog(null, "Please select appropriate row");
            return;
        }
        PrescribeMedicinesJPanel pmjp = new PrescribeMedicinesJPanel(dwahjp, jPanel2, enterprise, account, request);
        jPanel2.add("PrescribeMedicinesJPanel",pmjp);
        CardLayout layout = (CardLayout)jPanel2.getLayout();
        layout.next(jPanel2);   
    }//GEN-LAST:event_precribeMedicinesLblMouseClicked

    private void requestTestLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_requestTestLblMouseClicked
        // TODO add your handling code here:
        if(dwahjp.getSelectedPatient() == null){
            JOptionPane.showMessageDialog(null, "Please select appropriate row");
            return;
        }
        WorkRequest request = (WorkRequest)dwahjp.getSelectedPatient();
        RequestTestJPanel rtjp = new RequestTestJPanel(dwahjp, jPanel2, enterprise, account, request);
        jPanel2.add("RequestTestJPanel",rtjp);
        CardLayout layout = (CardLayout)jPanel2.getLayout();
        layout.next(jPanel2);
                
    }//GEN-LAST:event_requestTestLblMouseClicked

    private void logoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutBtnActionPerformed
        // TODO add your handling code here:
        jPanel.remove(this);
        CardLayout layout = (CardLayout)jPanel.getLayout();
        layout.previous(jPanel);
        dB4OUtil.storeSystem(system);
    }//GEN-LAST:event_logoutBtnActionPerformed

    private void viewTestLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewTestLblMouseClicked
        // TODO add your handling code here:
        if(dwahjp.getLabTestRequest() == null){
            JOptionPane.showMessageDialog(null, "Please select appropriate row");
            return;
        }
        ViewTestStatusJPanel vtsjp = new ViewTestStatusJPanel(jPanel2, dwahjp.getLabTestRequest());
        jPanel2.add("ViewTestStatusJPanel", vtsjp);
        CardLayout layout = (CardLayout)jPanel2.getLayout();
        layout.next(jPanel2);
    }//GEN-LAST:event_viewTestLblMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JButton logoutBtn;
    private javax.swing.JLabel precribeMedicinesLbl;
    private javax.swing.JLabel requestTestLbl;
    private javax.swing.JLabel viewTestLbl;
    // End of variables declaration//GEN-END:variables
}
