/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.DoctorRole;

import Business.Drug.Drug;
import Business.Enterprise.Enterprise;
import Business.Enterprise.HelpCenterEnterprise;
import Business.Homeless.HomelessIndividual;
import Business.Organization.DoctorOrganization;
import Business.Organization.LabAssistantOrganization;
import Business.Organization.NurseOrganization;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.WorkRequest.LabTestWorkRequest;
import Business.WorkRequest.PrescribeMedsWorkRequest;
import Business.WorkRequest.ReceptionistWorkRequest;
import Business.WorkRequest.WorkRequest;
import java.awt.CardLayout;
import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Varada
 */
public class PrescribeMedicinesJPanel extends javax.swing.JPanel {

    /**
     * Creates new form PrescribeMedicinesJPanel
     */
    JPanel jPanel2;
    HelpCenterEnterprise enterprise;
    UserAccount userAccount;
    HomelessIndividual homeless;
    DoctorWorkAreaHomeJPanel dwahjp;
    LabTestWorkRequest request;
    boolean medReq= false;
    
    public PrescribeMedicinesJPanel(DoctorWorkAreaHomeJPanel dwahjp, JPanel jPanel2, HelpCenterEnterprise enterprise, UserAccount userAccount, WorkRequest request) {
        initComponents();
        this.jPanel2 = jPanel2;
        this.enterprise = enterprise;
        this.userAccount = userAccount;
        this.homeless = request.getHomeless();
        this.dwahjp = dwahjp;
        if(request instanceof ReceptionistWorkRequest){
            this.request = new LabTestWorkRequest();
            medReq = true;
        }else
            this.request = (LabTestWorkRequest)request;
        setFields();
        populateComboBox();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        patientNameTxtField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        patientIdTxtField = new javax.swing.JTextField();
        submitBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        prescriptionTable = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        drugComboBox = new javax.swing.JComboBox<String>();
        quantityTxtField = new javax.swing.JTextField();
        addPrescriptionBtn = new javax.swing.JButton();
        removeDrugBtn = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(120, 168, 252));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Prescribe Medicines");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 24, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Patient Name:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(116, 77, 149, -1));

        patientNameTxtField.setEditable(false);
        add(patientNameTxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(271, 76, 244, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Patient ID:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(116, 121, -1, -1));

        patientIdTxtField.setEditable(false);
        add(patientIdTxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(271, 120, 244, -1));

        submitBtn.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        submitBtn.setText("Submit");
        submitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitBtnActionPerformed(evt);
            }
        });
        add(submitBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 507, -1, -1));

        backBtn.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        backBtn.setText("Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        add(backBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 507, -1, -1));

        prescriptionTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Drug Name", "Quantity"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(prescriptionTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 328, -1, 102));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Medicines:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(116, 176, 149, -1));

        add(drugComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(271, 175, 244, -1));
        add(quantityTxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(271, 221, 86, -1));

        addPrescriptionBtn.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        addPrescriptionBtn.setText("Add To Prescription");
        addPrescriptionBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addPrescriptionBtnActionPerformed(evt);
            }
        });
        add(addPrescriptionBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(364, 279, -1, -1));

        removeDrugBtn.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        removeDrugBtn.setText("Remove Item");
        removeDrugBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeDrugBtnActionPerformed(evt);
            }
        });
        add(removeDrugBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(414, 446, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Quantity:");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(116, 222, -1, -1));
    }// </editor-fold>//GEN-END:initComponents
    private void setFields(){
        patientIdTxtField.setText(String.valueOf(homeless.getId()));
        patientNameTxtField.setText(homeless.getFirstName()+" "+homeless.getLastName());
        patientIdTxtField.setEnabled(false);
        patientNameTxtField.setEnabled(false);
    }
    
    private void submitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitBtnActionPerformed
        // TODO add your handling code here:
        
        WorkRequest.WorkStatusType type = WorkRequest.WorkStatusType.Prescribed;
        
        request.setSender(userAccount);
        request.setRequestDate(new Date());
        request.setTestStatus(type.getValue());
        request.setHomeless(homeless);
        
        Organization org = null;
        for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()){
            if (organization instanceof NurseOrganization){
                org = organization;
                if(medReq){
                    org.getWorkQueue().getWorkRequestList().add(request);
                    userAccount.getWorkQueue().getWorkRequestList().add(request);
                }else{
                    org.getWorkQueue().getWorkRequestList().set(org.getWorkQueue().getWorkRequestList().indexOf(request), request);
                    userAccount.getWorkQueue().getWorkRequestList().set(userAccount.getWorkQueue().getWorkRequestList().indexOf(request), request);
                }
                break;
            }
        }
        for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()){
            if (organization instanceof DoctorOrganization){
                org = organization;
                for(Iterator<WorkRequest> iterator = org.getWorkQueue().getWorkRequestList().iterator(); iterator.hasNext();){
                    WorkRequest req = iterator.next();
                    if(req.getHomeless() == homeless){
                        iterator.remove();
                    }
                }
                break;
            }
        }
        
        
        
        JOptionPane.showMessageDialog(null, "Prescription sent");
    }//GEN-LAST:event_submitBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        jPanel2.remove(this);
        CardLayout layout = (CardLayout)jPanel2.getLayout();
        layout.previous(jPanel2);
        dwahjp.populateAccountRequests();
        dwahjp.populateWorkRequests();
    }//GEN-LAST:event_backBtnActionPerformed
    
    private void populatePrescriptionTable(){
        DefaultTableModel model = (DefaultTableModel)prescriptionTable.getModel();
        model.setRowCount(0);
        Object []row = new Object[2];
        for(Map.Entry mapElement: request.getPrescription().entrySet()){
            row[0] = mapElement.getKey();
            row[1] = mapElement.getValue();
            model.addRow(row);
        }
    }
    
    private void populateComboBox(){
        drugComboBox.removeAllItems();
        for(Drug med : enterprise.getDrugList().values()){
            drugComboBox.addItem(med.getName());
        }
    }
    private void addPrescriptionBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addPrescriptionBtnActionPerformed
        // TODO add your handling code here:
        String medicine = (String)drugComboBox.getSelectedItem();
        Integer quantity = Integer.parseInt(quantityTxtField.getText());
        request.getPrescription().put(medicine, quantity);
        populatePrescriptionTable();
    }//GEN-LAST:event_addPrescriptionBtnActionPerformed
    
    private void removeDrugBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeDrugBtnActionPerformed
        // TODO add your handling code here:
        String medicine = String.valueOf(prescriptionTable.getValueAt(prescriptionTable.getSelectedRow(),0));
        request.getPrescription().remove(medicine);
        populatePrescriptionTable();
    }//GEN-LAST:event_removeDrugBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addPrescriptionBtn;
    private javax.swing.JButton backBtn;
    private javax.swing.JComboBox<String> drugComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField patientIdTxtField;
    private javax.swing.JTextField patientNameTxtField;
    private javax.swing.JTable prescriptionTable;
    private javax.swing.JTextField quantityTxtField;
    private javax.swing.JButton removeDrugBtn;
    private javax.swing.JButton submitBtn;
    // End of variables declaration//GEN-END:variables
}
