/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.LabAssistantRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Enterprise.HospitalEnterprise;
import Business.Network.Network;
import Business.UserAccount.UserAccount;
import Business.WorkRequest.LabTestWorkRequest;
import Business.WorkRequest.PrescribeMedsWorkRequest;
import Business.WorkRequest.SupplyDrugsWorkRequest;
import Business.WorkRequest.WorkRequest;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Varada
 */
public class LabAssistantHomeJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ProcessRequestJPanel
     */
    JPanel jpanel;
    UserAccount account;
    HospitalEnterprise enterprise;
    EcoSystem ecosystem;
    public LabAssistantHomeJPanel(JPanel jpanel, UserAccount account, HospitalEnterprise enterprise, EcoSystem ecosystem) {
        initComponents();
        this.jpanel = jpanel;
        this.account = account;
        this.enterprise = enterprise;
        this.ecosystem = ecosystem;
        populateRequestsTable();
        populateAccountRequestsTable();
    }

    public void populateRequestsTable(){
        DefaultTableModel model = (DefaultTableModel)labRequestTbl.getModel();
        model.setRowCount(0);
        Object row[] = new Object[4];
        for(Network network: ecosystem.getNetworkList()){
            for(Enterprise ent: network.getEnterpriseDirectory().getEnterpriseList()){
                if(this.enterprise == ent){
                    for(WorkRequest request: ent.getWorkQueue().getWorkRequestList()){
                        if(request instanceof LabTestWorkRequest){
                            LabTestWorkRequest labReq = (LabTestWorkRequest)request;
                            row[0] = labReq;
                            row[1] = labReq.getEnterprise();
                            row[2] = labReq.getSender();
                            row[3] = labReq.getTestType();
                            model.addRow(row);
                        }
                    }
                    break;
                }
            }
        }
        
    }
    
    public void populateAccountRequestsTable(){
        DefaultTableModel model = (DefaultTableModel)requestListTbl.getModel();
        model.setRowCount(0);
        
        for(WorkRequest request: account.getWorkQueue().getWorkRequestList()){
            Object []row = new Object[4];
            LabTestWorkRequest labRequest = (LabTestWorkRequest) request;
            row[0] = labRequest;
            row[1] = labRequest.getHomeless().getFirstName()+labRequest.getHomeless().getLastName();
            row[2] = labRequest.getTestType();
            row[3] = labRequest.getTestStatus();
            model.addRow(row);
        }
    }
    
    public WorkRequest getSelectedWorkRequest(){
        if(labRequestTbl.getSelectedRow()<0){
            return null;
        }
        return (LabTestWorkRequest)labRequestTbl.getValueAt(labRequestTbl.getSelectedRow(), 0);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        labRequestTbl = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        requestListTbl = new javax.swing.JTable();

        setBackground(new java.awt.Color(120, 168, 252));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labRequestTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Sample Id", "Enterprise", "Doctor Name", "Test Name"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(labRequestTbl);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(98, 99, 503, 163));

        requestListTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Sample Id", "Enterprise", "Test Name", "Test Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(requestListTbl);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(98, 354, 503, 163));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable labRequestTbl;
    private javax.swing.JTable requestListTbl;
    // End of variables declaration//GEN-END:variables
}
