/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.LabAssistantRole;

import Business.Enterprise.Enterprise;
import Business.Enterprise.HospitalEnterprise;
import Business.Network.Network;
import Business.UserAccount.UserAccount;
import Business.WorkRequest.LabTestWorkRequest;
import Business.WorkRequest.WorkRequest;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Varada
 */
public class ProcessRequestJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ProcessRequestJPanel
     */
    LabAssistantHomeJPanel lahjp;
    JPanel jpanel;
    HospitalEnterprise enterprise;
    UserAccount account;
    LabTestWorkRequest request;
    public ProcessRequestJPanel(LabAssistantHomeJPanel lahjp, JPanel jpanel, HospitalEnterprise enterprise, UserAccount account, WorkRequest request) {
        initComponents();
        this.lahjp = lahjp;
        this.jpanel = jpanel;
        this.enterprise = enterprise;
        this.account = account;
        this.request = (LabTestWorkRequest)request;
        setFields();
    }

    private void setFields(){
        sampleIdTxtField.setText(request.getTestSampleId());
        testNameTxtField.setText(request.getTestType());
        testDescTxtField.setText(request.getMessage());
        sampleIdTxtField.setEnabled(false);
        testNameTxtField.setEnabled(false);
        testDescTxtField.setEnabled(false);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        sampleIdTxtField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        testNameTxtField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        testResultTxtField = new javax.swing.JTextArea();
        processBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        testDescTxtField = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(120, 168, 252));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Sample Id:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(166, 57, -1, -1));

        sampleIdTxtField.setEditable(false);
        add(sampleIdTxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(336, 58, 166, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Test Name:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(159, 102, -1, -1));

        testNameTxtField.setEditable(false);
        add(testNameTxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(336, 103, 166, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Test Results:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(148, 261, -1, -1));

        testResultTxtField.setColumns(20);
        testResultTxtField.setRows(5);
        jScrollPane1.setViewportView(testResultTxtField);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(336, 261, -1, -1));

        processBtn.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        processBtn.setText("Process");
        processBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                processBtnActionPerformed(evt);
            }
        });
        add(processBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(379, 409, -1, -1));

        backBtn.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        backBtn.setText("Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        add(backBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 409, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Test Description:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(112, 147, -1, -1));

        testDescTxtField.setEditable(false);
        testDescTxtField.setColumns(20);
        testDescTxtField.setRows(5);
        jScrollPane2.setViewportView(testDescTxtField);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(336, 147, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Process Request");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(295, 22, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void processBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_processBtnActionPerformed
        // TODO add your handling code here:
        String testResult = testResultTxtField.getText();
        this.request.setTestResult(testResult);
        this.request.setTestStatus(WorkRequest.WorkStatusType.Processed.getValue());
        account.getWorkQueue().getWorkRequestList().add(request);
        this.enterprise.getWorkQueue().getWorkRequestList().remove(request);
        JOptionPane.showMessageDialog(null, "Test Sample Processed");
    }//GEN-LAST:event_processBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        jpanel.remove(this);
        CardLayout layout = (CardLayout)jpanel.getLayout();
        layout.previous(jpanel);
        lahjp.populateRequestsTable();
        lahjp.populateAccountRequestsTable();
    }//GEN-LAST:event_backBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton processBtn;
    private javax.swing.JTextField sampleIdTxtField;
    private javax.swing.JTextArea testDescTxtField;
    private javax.swing.JTextField testNameTxtField;
    private javax.swing.JTextArea testResultTxtField;
    // End of variables declaration//GEN-END:variables
}
