/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.FoodManager;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Enterprise.FoodEnterprise;
import Business.Enterprise.HelpCenterEnterprise;
import Business.FoodPackets.FoodPackets;
import java.util.Date;
import javax.swing.table.DefaultTableModel;
import Business.FoodPackets.FoodPacketsDirectory;
import Business.Network.Network;
import java.awt.CardLayout;
import java.util.HashMap;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Varada
 */
public class AddFoodPacketsJPanel extends javax.swing.JPanel {

    /**
     * Creates new form AddFoodPacketsJPanel
     */
    FoodEnterprise foodEnterprise;
    JPanel jpanel2;
    FoodPackets fp;
    EcoSystem system;
    public AddFoodPacketsJPanel(JPanel jpanel2, FoodEnterprise foodEnterprise,  EcoSystem system) {
        initComponents();
        this.jpanel2 = jpanel2;
        this.foodEnterprise = foodEnterprise;
        this.system=system;
        
        

    }

    public void populateFoodPackets() {
        DefaultTableModel model = (DefaultTableModel) foodPacketTbl.getModel();
        model.setRowCount(0);

        for (FoodPackets foodPacket : foodEnterprise.getFoodPacketDirectory().getFoodPacketDirectory()) {
            Object[] row = new Object[5];
            row[0] = Integer.parseInt(batchIDtxtField.getText());
            row[1] = foodPacket;
            row[2] = foodPacket.getSent();
            row[3] = foodPacket.getExpiry();
            row[4] = foodPacket.getQuantity();
            model.addRow(row);

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        batchIDtxtField = new javax.swing.JTextField();
        senderIDtxtField = new javax.swing.JTextField();
        dateSent = new org.jdesktop.swingx.JXDatePicker();
        dateOfExpiry = new org.jdesktop.swingx.JXDatePicker();
        quantityTxtField = new javax.swing.JTextField();
        addBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        foodPacketTbl = new javax.swing.JTable();
        sendFPbtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(120, 168, 252));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Batch ID:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(91, 79, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Sender ID:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(91, 123, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Date Sent:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(91, 168, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Date of Expiry:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(91, 212, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Quantity:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(91, 256, -1, -1));
        add(batchIDtxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(241, 78, 149, -1));
        add(senderIDtxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(241, 122, 149, -1));
        add(dateSent, new org.netbeans.lib.awtextra.AbsoluteConstraints(241, 166, -1, -1));
        add(dateOfExpiry, new org.netbeans.lib.awtextra.AbsoluteConstraints(241, 210, -1, -1));

        quantityTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quantityTxtFieldActionPerformed(evt);
            }
        });
        add(quantityTxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(241, 256, 149, -1));

        addBtn.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        addBtn.setText("Add");
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });
        add(addBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(327, 300, -1, -1));

        foodPacketTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Batch ID", "Sender ID", "Date Sent", "Date of Expiry", "Quantity"
            }
        ));
        jScrollPane1.setViewportView(foodPacketTbl);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(78, 363, 593, 98));

        sendFPbtn.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        sendFPbtn.setText("Send Food Packet");
        sendFPbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendFPbtnActionPerformed(evt);
            }
        });
        add(sendFPbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(504, 494, -1, -1));

        backBtn.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        backBtn.setText("Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        add(backBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 494, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Add Food Packets");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(213, 25, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void quantityTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quantityTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_quantityTxtFieldActionPerformed

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        // TODO add your handling code here:
        int batchId = Integer.parseInt(batchIDtxtField.getText());
        int senderID = Integer.parseInt(senderIDtxtField.getText());
        Date sentDate = dateSent.getDate();
        Date expDate = dateOfExpiry.getDate();
        int quantity = Integer.parseInt(quantityTxtField.getText());
        
        FoodPackets foodPacket = new FoodPackets(senderID, sentDate, expDate, quantity);
        foodEnterprise.getFoodPacketDirectory().getFoodPacketDirectory().add(foodPacket);
        
        batchIDtxtField.setText(String.valueOf(batchId));
        senderIDtxtField.setText(String.valueOf(senderID));
        dateSent.setDate(sentDate);
        dateOfExpiry.setDate(expDate);
        quantityTxtField.setText(String.valueOf(quantity));
        JOptionPane.showMessageDialog(null, "Food Packet Added!");

        populateFoodPackets();

    }//GEN-LAST:event_addBtnActionPerformed

    private void sendFPbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendFPbtnActionPerformed
        // TODO add your handling code here:
        //HashMap<Integer, FoodPackets> fl = foodEnterprise.getFoodList();
        //fl.put(Integer.parseInt((String)foodPacketTbl.getValueAt(foodPacketTbl.getSelectedRow(), 0)), (FoodPackets)foodPacketTbl.getValueAt(foodPacketTbl.getSelectedRow(), 1));
        fp = (FoodPackets) foodPacketTbl.getValueAt(foodPacketTbl.getSelectedRow(), 1);
        for(Network network: system.getNetworkList()){
            for(Enterprise ent: network.getEnterpriseDirectory().getEnterpriseList()){
                if(ent instanceof HelpCenterEnterprise){
                    HelpCenterEnterprise help = (HelpCenterEnterprise)ent;
                    help.getFoodPacketDirectory().getFoodPacketDirectory().add(fp);
                
            }
                
            }
        }
        JOptionPane.showMessageDialog(null, "Food Packet Sent to Help Center!");
    }//GEN-LAST:event_sendFPbtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        jpanel2.remove(this);
        CardLayout layout = (CardLayout)jpanel2.getLayout();
        layout.previous(jpanel2);
    }//GEN-LAST:event_backBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBtn;
    private javax.swing.JButton backBtn;
    private javax.swing.JTextField batchIDtxtField;
    private org.jdesktop.swingx.JXDatePicker dateOfExpiry;
    private org.jdesktop.swingx.JXDatePicker dateSent;
    private javax.swing.JTable foodPacketTbl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField quantityTxtField;
    private javax.swing.JButton sendFPbtn;
    private javax.swing.JTextField senderIDtxtField;
    // End of variables declaration//GEN-END:variables
}
