/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.ReceptionistRole;

import Business.Enterprise.Enterprise;
import Business.Homeless.HomelessIndividual;
import Business.Organization.DoctorOrganization;
import Business.Organization.HousingOrganization;
import Business.Organization.LabAssistantOrganization;
import Business.Organization.Organization;
import Business.Organization.StockerOrganization;
import Business.UserAccount.UserAccount;
import Business.WorkRequest.ReceptionistWorkRequest;
import Business.WorkRequest.WorkRequest;
import java.awt.CardLayout;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Yash Lekhwani
 */
public class RaiseWorkRequest extends javax.swing.JPanel {

    /**
     * Creates new form RaiseWorkRequest
     */
    JPanel jPanel2;
    Enterprise enterprise;
    UserAccount userAccount;
    HomelessIndividual homeless;
    RaiseWorkRequest(JPanel jPanel2, Enterprise enterprise, UserAccount userAccount, HomelessIndividual homeless) {
        initComponents();
        this.jPanel2 = jPanel2;
        this.enterprise = enterprise;
        this.userAccount= userAccount;
        this.homeless = homeless;
        populateRequestComboBox();
    }
    
    private static void populateRequestComboBox(){
        requestComboBox.addItem("Diagnosis Request");
        requestComboBox.addItem("Food Request");
        requestComboBox.addItem("Shelter Request");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        registerIndividual = new javax.swing.JLabel();
        requestMessageTxtField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        requestComboBox = new javax.swing.JComboBox();
        raiseRequestBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("First Name");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("HID");

        setBackground(new java.awt.Color(120, 168, 252));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        registerIndividual.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        registerIndividual.setForeground(new java.awt.Color(255, 255, 255));
        registerIndividual.setText("Raise a Request");
        registerIndividual.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                registerIndividualMouseClicked(evt);
            }
        });
        add(registerIndividual, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 31, -1, -1));

        requestMessageTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                requestMessageTxtFieldActionPerformed(evt);
            }
        });
        add(requestMessageTxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(275, 153, 170, 107));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Request");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 187, 106, 37));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Category of Request");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 107, 166, 37));

        requestComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                requestComboBoxActionPerformed(evt);
            }
        });
        add(requestComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(275, 113, 170, -1));

        raiseRequestBtn.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        raiseRequestBtn.setText("SUBMIT");
        raiseRequestBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                raiseRequestBtnActionPerformed(evt);
            }
        });
        add(raiseRequestBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(312, 278, 133, -1));

        backBtn.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        backBtn.setText("BACK");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        add(backBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 278, 133, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void registerIndividualMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registerIndividualMouseClicked
        // TODO add your handling code here:
       
    }//GEN-LAST:event_registerIndividualMouseClicked

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void requestMessageTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_requestMessageTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_requestMessageTxtFieldActionPerformed

    private void raiseRequestBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_raiseRequestBtnActionPerformed
        // TODO add your handling code here:
        String requestMessage = requestMessageTxtField.getText();
        String status = String.valueOf(requestComboBox.getSelectedItem());
        ReceptionistWorkRequest request = new ReceptionistWorkRequest();
        request.setMessage(requestMessage);
        request.setSender(userAccount);
        request.setRequestDate(new Date());
        request.setResolveDate(null);
        
        request.setRequestStatus(WorkRequest.WorkStatusType.Pending.getValue());
        request.setHomeless(homeless);
        Organization org = null;
        for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()){
            if (status=="Diagnosis Request" && organization instanceof DoctorOrganization){
                org = organization;
                break;
            }else if(status=="Food Request" && organization instanceof StockerOrganization){
                org = organization;
                break;
            }else if(status=="Shelter Request" && organization instanceof HousingOrganization){
                org = organization;
                break;
            }
        }
        if (org!=null){
            org.getWorkQueue().getWorkRequestList().add(request);
            userAccount.getWorkQueue().getWorkRequestList().add(request);
        }
        
        JOptionPane.showMessageDialog(null, status+"ed");
    }//GEN-LAST:event_raiseRequestBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        jPanel2.remove(this);
        CardLayout layout = (CardLayout)jPanel2.getLayout();
        layout.previous(jPanel2);
    }//GEN-LAST:event_backBtnActionPerformed

    private void requestComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_requestComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_requestComboBoxActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JButton raiseRequestBtn;
    private javax.swing.JLabel registerIndividual;
    private static javax.swing.JComboBox requestComboBox;
    private javax.swing.JTextField requestMessageTxtField;
    // End of variables declaration//GEN-END:variables
}
