/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.ReceptionistRole;


import Business.DB4OUtil.DB4OUtil;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Enterprise.HelpCenterEnterprise;
import Business.Homeless.HomelessIndividual;
import Business.UserAccount.UserAccount;

import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Yash Lekhwani
 */
public class ReceptionistWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ReceptionistWorkArea
     */
    JPanel jpanel;
    HelpCenterEnterprise enterprise;
    UserAccount account;
    EcoSystem ecosystem;
    ReceptionistHomePanel rh;
    private DB4OUtil dB4OUtil = DB4OUtil.getInstance();
    public ReceptionistWorkAreaJPanel(JPanel jpanel, EcoSystem ecosystem, HelpCenterEnterprise enterprise, UserAccount account) {
        initComponents();
        this.jpanel = jpanel;
        this.enterprise = enterprise;
        this.account = account;
        this.ecosystem = ecosystem;
        this.rh= new ReceptionistHomePanel(jPanel2,enterprise);
        jPanel2.add("ReceptionistHomePanel", rh);
        CardLayout layout = (CardLayout)jPanel2.getLayout();
        layout.next(jPanel2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        registerIndividual = new javax.swing.JLabel();
        raiserequest = new javax.swing.JLabel();
        manageEnterpriseAdminLbl = new javax.swing.JLabel();
        Logout = new javax.swing.JButton();

        jPanel2.setBackground(new java.awt.Color(120, 168, 252));
        jPanel2.setLayout(new java.awt.CardLayout());
        jSplitPane1.setRightComponent(jPanel2);

        jPanel1.setBackground(new java.awt.Color(71, 120, 197));

        registerIndividual.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        registerIndividual.setForeground(new java.awt.Color(255, 255, 255));
        registerIndividual.setText("Register Individuals");
        registerIndividual.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                registerIndividualMouseClicked(evt);
            }
        });

        raiserequest.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        raiserequest.setForeground(new java.awt.Color(255, 255, 255));
        raiserequest.setText("Raise A Request");
        raiserequest.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                raiserequestMouseClicked(evt);
            }
        });

        manageEnterpriseAdminLbl.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        manageEnterpriseAdminLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                manageEnterpriseAdminLblMouseClicked(evt);
            }
        });

        Logout.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Logout.setText("LOGOUT");
        Logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(raiserequest, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(registerIndividual, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(manageEnterpriseAdminLbl)
                                    .addComponent(Logout))
                                .addGap(0, 140, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(registerIndividual)
                .addGap(27, 27, 27)
                .addComponent(raiserequest)
                .addGap(27, 27, 27)
                .addComponent(manageEnterpriseAdminLbl)
                .addGap(27, 27, 27)
                .addComponent(Logout)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jSplitPane1.setLeftComponent(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 669, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 502, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void registerIndividualMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registerIndividualMouseClicked
        // TODO add your handling code here:
        RegisterIndividual r = new RegisterIndividual(jPanel2,enterprise);
        jPanel2.add("RegisterIndividual", r);
        CardLayout layout = (CardLayout)jPanel2.getLayout();
        layout.next(jPanel2);

    }//GEN-LAST:event_registerIndividualMouseClicked

    private void raiserequestMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_raiserequestMouseClicked
        // TODO add your handling code here:
        HomelessIndividual homeless = rh.getSelectedHomeless();
        if(homeless!=null){
            RaiseWorkRequest rw = new RaiseWorkRequest(jPanel2, enterprise, account, homeless);
            jPanel2.add("ManageEnterpriseJPanel", rw);
            CardLayout layout = (CardLayout)jPanel2.getLayout();
            layout.next(jPanel2);
        }else{
            JOptionPane.showMessageDialog(null, "Please Select a record first");
        }
        
    }//GEN-LAST:event_raiserequestMouseClicked

    private void manageEnterpriseAdminLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manageEnterpriseAdminLblMouseClicked
        // TODO add your handling code here:
       
    }//GEN-LAST:event_manageEnterpriseAdminLblMouseClicked

    private void LogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutActionPerformed
        // TODO add your handling code here:
        jpanel.remove(this);
        CardLayout layout = (CardLayout)jpanel.getLayout();
        layout.previous(jpanel);
        dB4OUtil.storeSystem(ecosystem);
    }//GEN-LAST:event_LogoutActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Logout;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JLabel manageEnterpriseAdminLbl;
    private javax.swing.JLabel raiserequest;
    private javax.swing.JLabel registerIndividual;
    // End of variables declaration//GEN-END:variables
}
