/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.HousingManagerRole;

import Business.UserAccount.UserAccount;
import Business.WorkRequest.HousingWorkRequest;
import Business.WorkRequest.WorkRequest;
import java.awt.CardLayout;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Yash Lekhwani
 */
public class GeneratedTicketsJPanel extends javax.swing.JPanel {

    /**
     * Creates new form GeneratedTicketsJPanel
     */
    JPanel jpanel;
    UserAccount account;
    public GeneratedTicketsJPanel(JPanel jpanel, UserAccount account) {
        initComponents();
        this.jpanel = jpanel;
        this.account = account;
        populateTicketsTable();
    }

    private void populateTicketsTable(){
        DefaultTableModel model = (DefaultTableModel)ticketsTbl.getModel();
        model.setRowCount(0);
        Object row[] = new Object[4];
        for(WorkRequest request: account.getWorkQueue().getWorkRequestList()){
            HousingWorkRequest housing = (HousingWorkRequest)request;
            row[0] = housing;
            row[1] = housing.getHomeless().getFirstName()+ " " + housing.getHomeless().getLastName();
            row[2] = housing.getAcco().getAccomodationName();
            row[3] = housing.getCheckIn();
            model.addRow(row);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        ticketsTbl = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        homelessTxtField = new javax.swing.JTextField();
        accoNameTxtField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        accoLocationTxtField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        checkInTxtField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        checkOutTxtField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        viewBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(120, 168, 252));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ticketsTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Ticket Id", "Homeless Name", "Accommodation", "CheckIn"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(ticketsTbl);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(159, 55, -1, 160));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Homeless Name:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(146, 273, -1, -1));

        homelessTxtField.setEditable(false);
        homelessTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homelessTxtFieldActionPerformed(evt);
            }
        });
        add(homelessTxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(348, 274, 263, -1));

        accoNameTxtField.setEditable(false);
        add(accoNameTxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(348, 319, 263, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Accomodation Name:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(146, 318, -1, -1));

        accoLocationTxtField.setEditable(false);
        add(accoLocationTxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(348, 364, 263, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Location:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(146, 363, -1, -1));

        checkInTxtField.setEditable(false);
        add(checkInTxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(348, 409, 263, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Check In:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(146, 408, -1, -1));

        checkOutTxtField.setEditable(false);
        add(checkOutTxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(348, 454, 263, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Check Out:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(146, 453, -1, -1));

        viewBtn.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        viewBtn.setText("View");
        viewBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewBtnActionPerformed(evt);
            }
        });
        add(viewBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 231, -1, -1));

        backBtn.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        backBtn.setText("Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        add(backBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(146, 498, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Generated Tickets");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 14, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void viewBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewBtnActionPerformed
        // TODO add your handling code here:
        HousingWorkRequest request = (HousingWorkRequest)ticketsTbl.getValueAt(ticketsTbl.getSelectedRow(), 0);
        homelessTxtField.setText(request.getHomeless().getFirstName()+" "+request.getHomeless().getLastName());
        accoNameTxtField.setText(request.getAcco().getAccomodationName());
        accoLocationTxtField.setText(request.getAcco().getLocation());
        checkInTxtField.setText(request.getCheckIn().toString());
        checkOutTxtField.setText(request.getCheckOut().toString());
    }//GEN-LAST:event_viewBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        jpanel.remove(this);
        CardLayout layout = (CardLayout)jpanel.getLayout();
        layout.previous(jpanel);
    }//GEN-LAST:event_backBtnActionPerformed

    private void homelessTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homelessTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_homelessTxtFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField accoLocationTxtField;
    private javax.swing.JTextField accoNameTxtField;
    private javax.swing.JButton backBtn;
    private javax.swing.JTextField checkInTxtField;
    private javax.swing.JTextField checkOutTxtField;
    private javax.swing.JTextField homelessTxtField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable ticketsTbl;
    private javax.swing.JButton viewBtn;
    // End of variables declaration//GEN-END:variables
}
